### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy' - heroku deployment

### ISSUE THREAD

**Issue by Isquare1** [LeeKamentsky/python-javabridge#191]
Hi, I'm deploying a web app to heroku and the app seems to require python-javabridge. As it tries to download python-javabridge-4.0.0.tar.gz to its server, I get the error: 

```
remote:        Collecting python-javabridge==4.0.0
remote:          Downloading python-javabridge-4.0.0.tar.gz (1.3 MB)
remote:            ERROR: Command errored out with exit status 1:
remote:             command: /app/.heroku/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-um4hs34c/python-javabridge/setup.py'"'"'; __file__='"'"'/tmp/pip-install-um4hs34c/python-javabridge/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-bn8fvmq1
remote:                 cwd: /tmp/pip-install-um4hs34c/python-javabridge/
remote:            Complete output (7 lines):
remote:            Traceback (most recent call last):
remote:              File "<string>", line 1, in <module>
remote:              File "/tmp/pip-install-um4hs34c/python-javabridge/setup.py", line
412, in <module>
remote:                ext_modules=ext_modules(),
remote:              File "/tmp/pip-install-um4hs34c/python-javabridge/setup.py", line
100, in ext_modules
remote:                from numpy import get_include
remote:            ModuleNotFoundError: No module named 'numpy'
remote:            ----------------------------------------
remote:        ERROR: Command errored out with exit status 1: python setup.py egg_info
Check the logs for full command output.
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
```

I read around this error and it seems to be a common issue that the get_include function is called from the setup.py file of a package before numpy has been installed, however, I am not sure how to fix it myself (or to verify this is indeed the problem here). Of course I have pip installed numpy and javabridge on my local machine and this works fine, but not sure what happens when it tries to install it on the heroku server. I'm using Anaconda 3 Python 3.7 and Spyder IDE (and Spyder terminal for the commands). 

Any help will be appreciated!

**Comment by LeeKamentsky** [comment]
Well, that's interesting. I release this code base as javabridge on Pypi (https://pypi.org/project/javabridge/), but CellProfiler seems to have forked and re-released the package as python-javabridge (https://pypi.org/project/python-javabridge). Maybe they've screwed it up - I'm not responsible or involved. I would find out what dependency of your app is using Javabridge and suggest to them that they either make javabridge a dependency of their app instead of python-javabridge or they should contact the developers of the fork and tell them to fix their code. Please file this bug at https://github.com/CellProfiler/python-javabridge/ instead of here.
