### ISSUE TITLE
Fail to start Java VM, second time. Linux

### ISSUE THREAD

**Issue by johncookds** [LeeKamentsky/python-javabridge#88]
Hello,

I have been running a python function that uses javabridge for some time on my mac and have had no problems. I have switched over to linux and have a bug where the Java VM fails to start on the second iteration. I have performed every check and tested every version of java, javabridge and the other packages I'm using that I can think of. The problem is below:

***Before this error the function is called once and performs very well
It uses this to start the VM:
     javabridge.start_vm(run_headless=True, max_heap_size = java_max_heap_size)
        javabridge.attach()

and this at the end to close it:
        javabridge.detach()
        javabridge.kill_vm()

***During the second iteration this problem occurs
This does not occur on my mac I believe because there is a separate process for starting a VM on a mac in jutil.py.

***This is the problem:
  env = vm.create(args)
  File "_javabridge.pyx", line 615, in _javabridge.JB_VM.create (_javabridge.c:6647)
RuntimeError: Failed to create Java VM. Return code = -1
No handlers could be found for logger "javabridge.jutil"
Traceback:
  javabridge.start_vm(run_headless=True, max_heap_size = java_max_heap_size)

  File "javabridge/jutil.py", line 312, in start_vm
    raise RuntimeError("Failed to start Java VM")

RuntimeError: Failed to start Java VM.

Any help would be greatly appreciated.

**Comment by LeeKamentsky** [comment]
Yup - that is a fundamental limitation - you can call `javabridge.start_vm` at most one time. I am really surprised you managed to restart the JVM on the Mac - it's not at all supported. It's very tricky to manage the JVM's scope so that it is instantiated only once and killed only once and unfortunately requires more thought than it deserves.

For more information, see http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4712793 which documents a simple test case that fails to restart the JVM after shutting it down.

In any case, thanks for using Javabridge, John and good luck.

**Comment by rupav** [comment]
So basically, on first iteration if I started JVM, did some work, and then stopped it using JVM.stop.
On next call, I don't need to start JVM again?

**Comment by rupav** [comment]
@LeeKamentsky  can you please have a look on https://stackoverflow.com/questions/51795945/after-stopping-jvm-unable-to-start-it-again

**Comment by LeeKamentsky** [comment]
I'm afraid it's not under our control. It's a limitation of the JVM itself. I would look at where the javabridge initialization is done in your app (or in  the library that's starting the javabridge) and make sure it's done only once.

**Comment by amber0309** [comment]
Just ran into this problem. I was wondering whether there were any ways to fix this now (Aug. 2019)? Much appreciated!

**Comment by amber0309** [comment]
> Yup - that is a fundamental limitation - you can call `javabridge.start_vm` at most one time. I am really surprised you managed to restart the JVM on the Mac - it's not at all supported. It's very tricky to manage the JVM's scope so that it is instantiated only once and killed only once and unfortunately requires more thought than it deserves.
> 
> For more information, see http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4712793 which documents a simple test case that fails to restart the JVM after shutting it down.
> 
> In any case, thanks for using Javabridge, John and good luck.

Just ran into this problem. I was wondering whether there were any ways to fix this now (Aug. 2019)? Much appreciated!

**Comment by LeeKamentsky** [comment]
Nope, I wish there were, but you will have to find some way to work around it if you plan to use the JVM at all.

**Comment by JJAA91** [comment]
I acknowledge this is a super old issue, and I apologize if this has been fixed in later versions of javabridge, but I have been struggling with this problem for a little while now and I think I have found a reliable work around. Hopefully others will find it helpful in some way.

The best work around I came across is to run what ever requires the JVM in a function on a separate process. For ease, I use an additional package called [pebble](https://pythonhosted.org/Pebble/#) for this, but you can certainly use the `multiprocessing` package in the standard library for the same effect. Below is an example of how I use it:

```
import javabridge
from pebble import concurrent, ProcessFuture


@concurrent.process
def my_function(*args, **kwargs):
    javabridge.start_vm()
    """
    Add the logic that depends on the JVM here, and return whatever you need to return
    """
    javabridge.kill_vm()
    return "your_results_here"


if __name__=="__main__":
    future: ProcessFuture = my_function(*args, **kwargs)
    results = future.results()
``` 
With this kind of architecture, I can run `my_function()` as many times as I like without experiencing that `RuntimeError`.
